# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utube.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(13, 13, 13);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(1000, 700))
        self.frame.setMaximumSize(QtCore.QSize(1000, 700))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(self.frame)
        self.main_frame.setMinimumSize(QtCore.QSize(1000, 700))
        self.main_frame.setMaximumSize(QtCore.QSize(1000, 700))
        self.main_frame.setAutoFillBackground(False)
        self.main_frame.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.Logo = QtWidgets.QFrame(self.main_frame)
        self.Logo.setGeometry(QtCore.QRect(326, 30, 361, 121))
        self.Logo.setStyleSheet("background-image: url(:/Logo/Logo_ong.png);\n"
"background-position: center;\n"
"background-repeat: norepeat;")
        self.Logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Logo.setObjectName("Logo")
        self.CampoLink = QtWidgets.QLineEdit(self.main_frame)
        self.CampoLink.setGeometry(QtCore.QRect(225, 230, 550, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.CampoLink.setFont(font)
        self.CampoLink.setStyleSheet("QLineEdit {\n"
"border: 2px solid;\n"
"border-radius:5px;\n"
"padding: 10px;\n"
"background-color: rgb(80, 80, 80);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QLineEdit:hover {\n"
"border: 2px solid rgb(55, 55, 55);}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(205, 54, 88)\n"
"}")
        self.CampoLink.setAlignment(QtCore.Qt.AlignCenter)
        self.CampoLink.setObjectName("CampoLink")
        self.Buscar = QtWidgets.QPushButton(self.main_frame)
        self.Buscar.setGeometry(QtCore.QRect(420, 280, 160, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Buscar.setFont(font)
        self.Buscar.setStyleSheet("QPushButton {\n"
"background-color: rgb(58, 19, 190);\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(49, 16, 167);\n"
"border: 2px solid rgb(50, 50, 50);\n"
"\n"
"}")
        self.Buscar.setObjectName("Buscar")
        self.Destino = QtWidgets.QPushButton(self.main_frame)
        self.Destino.setGeometry(QtCore.QRect(410, 160, 180, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Destino.setFont(font)
        self.Destino.setStyleSheet("QPushButton {\n"
"background-color: rgb(242, 25, 2);\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(214, 19, 1);\n"
"border: 2px solid rgb(50, 50, 50);\n"
"\n"
"}")
        self.Destino.setObjectName("Destino")
        self.bottom = QtWidgets.QFrame(self.main_frame)
        self.bottom.setGeometry(QtCore.QRect(0, 660, 1000, 40))
        self.bottom.setMinimumSize(QtCore.QSize(1000, 40))
        self.bottom.setMaximumSize(QtCore.QSize(1000, 40))
        self.bottom.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.copyright = QtWidgets.QLabel(self.bottom)
        font = QtGui.QFont()
        font.setFamily("Obadiah")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.copyright.setFont(font)
        self.copyright.setStyleSheet("color: rgb(255, 255, 255);")
        self.copyright.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.copyright.setObjectName("copyright")
        self.horizontalLayout_2.addWidget(self.copyright)
        self.TituloVideo = QtWidgets.QLabel(self.main_frame)
        self.TituloVideo.setGeometry(QtCore.QRect(75, 320, 850, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.TituloVideo.setFont(font)
        self.TituloVideo.setStyleSheet("color: rgb(255, 255, 255);")
        self.TituloVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.TituloVideo.setObjectName("TituloVideo")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_frame)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 370, 900, 281))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.FramePagina = QtWidgets.QFrame(self.page_2)
        self.FramePagina.setMinimumSize(QtCore.QSize(0, 250))
        self.FramePagina.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.FramePagina.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FramePagina.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FramePagina.setObjectName("FramePagina")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.FramePagina)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FrameThumb = QtWidgets.QFrame(self.FramePagina)
        self.FrameThumb.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.FrameThumb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameThumb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameThumb.setObjectName("FrameThumb")
        self.PlacetoThumb = QtWidgets.QLabel(self.FrameThumb)
        self.PlacetoThumb.setGeometry(QtCore.QRect(10, 10, 408, 201))
        self.PlacetoThumb.setMaximumSize(QtCore.QSize(500, 500))
        self.PlacetoThumb.setStyleSheet("")
        self.PlacetoThumb.setText("")
        self.PlacetoThumb.setObjectName("PlacetoThumb")
        self.horizontalLayout_3.addWidget(self.FrameThumb)
        self.BotoesDownload = QtWidgets.QFrame(self.FramePagina)
        self.BotoesDownload.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.BotoesDownload.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BotoesDownload.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BotoesDownload.setObjectName("BotoesDownload")
        self.Download_360p = QtWidgets.QPushButton(self.BotoesDownload)
        self.Download_360p.setGeometry(QtCore.QRect(134, 106, 190, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Download_360p.setFont(font)
        self.Download_360p.setStyleSheet("QPushButton {\n"
"background-color: rgb(58, 19, 190);\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(49, 16, 167);\n"
"border: 2px solid rgb(50, 50, 50);\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Video/filme.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Download_360p.setIcon(icon1)
        self.Download_360p.setObjectName("Download_360p")
        self.Download_HD = QtWidgets.QPushButton(self.BotoesDownload)
        self.Download_HD.setGeometry(QtCore.QRect(134, 62, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Download_HD.setFont(font)
        self.Download_HD.setStyleSheet("QPushButton {\n"
"background-color: rgb(242, 25, 2);\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(214, 19, 1);\n"
"border: 2px solid rgb(50, 50, 50);\n"
"\n"
"}")
        self.Download_HD.setIcon(icon1)
        self.Download_HD.setObjectName("Download_HD")
        self.Download_MP3 = QtWidgets.QPushButton(self.BotoesDownload)
        self.Download_MP3.setGeometry(QtCore.QRect(134, 150, 190, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Download_MP3.setFont(font)
        self.Download_MP3.setStyleSheet("QPushButton {\n"
"background-color: rgb(85, 44, 227);\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(75, 34, 217);\n"
"border: 2px solid rgb(50, 50, 50);\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/MP3/mp3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Download_MP3.setIcon(icon2)
        self.Download_MP3.setObjectName("Download_MP3")
        self.duracao = QtWidgets.QLabel(self.BotoesDownload)
        self.duracao.setGeometry(QtCore.QRect(134, 210, 190, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.duracao.setFont(font)
        self.duracao.setAlignment(QtCore.Qt.AlignCenter)
        self.duracao.setObjectName("duracao")
        self.horizontalLayout_3.addWidget(self.BotoesDownload)
        self.verticalLayout_3.addWidget(self.FramePagina)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ProcurandoVideo = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(48)
        self.ProcurandoVideo.setFont(font)
        self.ProcurandoVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.ProcurandoVideo.setObjectName("ProcurandoVideo")
        self.verticalLayout_2.addWidget(self.ProcurandoVideo)
        self.stackedWidget.addWidget(self.page)
        self.caminho = QtWidgets.QLabel(self.main_frame)
        self.caminho.setGeometry(QtCore.QRect(225, 210, 550, 16))
        self.caminho.setText("")
        self.caminho.setObjectName("caminho")
        self.horizontalLayout.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "U.Tube"))
        self.CampoLink.setPlaceholderText(_translate("MainWindow", "Cole o link do vídeo aqui"))
        self.Buscar.setText(_translate("MainWindow", "Buscar"))
        self.Destino.setText(_translate("MainWindow", "Selecionar destino"))
        self.copyright.setText(_translate("MainWindow", "Código Disponível no meu GitHub: https://github.com/WinstonDeMoura"))
        self.TituloVideo.setText(_translate("MainWindow", "Título do Vídeo"))
        self.Download_360p.setText(_translate("MainWindow", "Download 360p"))
        self.Download_HD.setText(_translate("MainWindow", "Download HD"))
        self.Download_MP3.setText(_translate("MainWindow", "Download MP3"))
        self.duracao.setText(_translate("MainWindow", "Duração"))
        self.ProcurandoVideo.setText(_translate("MainWindow", "Procurando Vídeo..."))
import Resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
